spring:
  application:
    name: firstproject

  datasource:
    url: jdbc:mysql://localhost:3306/webdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: webuser
    password: 54321
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8094
  servlet:
    encoding:
      force: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE